version: "3.9"

services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - app-network
    environment:
      - FLASK_SECRET_KEY=some-super-secret-string

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
